# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_warping', [dirname(__file__)])
        except ImportError:
            import _warping
            return _warping
        if fp is not None:
            try:
                _mod = imp.load_module('_warping', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _warping = swig_import_helper()
    del swig_import_helper
else:
    import _warping
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _warping.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _warping.SwigPyIterator_value(self)
    def incr(self, n=1): return _warping.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _warping.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _warping.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _warping.SwigPyIterator_equal(self, *args)
    def copy(self): return _warping.SwigPyIterator_copy(self)
    def next(self): return _warping.SwigPyIterator_next(self)
    def __next__(self): return _warping.SwigPyIterator___next__(self)
    def previous(self): return _warping.SwigPyIterator_previous(self)
    def advance(self, *args): return _warping.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _warping.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _warping.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _warping.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _warping.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _warping.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _warping.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _warping.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class Array(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Array, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Array, name)
    __repr__ = _swig_repr
    def iterator(self): return _warping.Array_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _warping.Array___nonzero__(self)
    def __bool__(self): return _warping.Array___bool__(self)
    def __len__(self): return _warping.Array___len__(self)
    def pop(self): return _warping.Array_pop(self)
    def __getslice__(self, *args): return _warping.Array___getslice__(self, *args)
    def __setslice__(self, *args): return _warping.Array___setslice__(self, *args)
    def __delslice__(self, *args): return _warping.Array___delslice__(self, *args)
    def __delitem__(self, *args): return _warping.Array___delitem__(self, *args)
    def __getitem__(self, *args): return _warping.Array___getitem__(self, *args)
    def __setitem__(self, *args): return _warping.Array___setitem__(self, *args)
    def append(self, *args): return _warping.Array_append(self, *args)
    def empty(self): return _warping.Array_empty(self)
    def size(self): return _warping.Array_size(self)
    def clear(self): return _warping.Array_clear(self)
    def swap(self, *args): return _warping.Array_swap(self, *args)
    def get_allocator(self): return _warping.Array_get_allocator(self)
    def begin(self): return _warping.Array_begin(self)
    def end(self): return _warping.Array_end(self)
    def rbegin(self): return _warping.Array_rbegin(self)
    def rend(self): return _warping.Array_rend(self)
    def pop_back(self): return _warping.Array_pop_back(self)
    def erase(self, *args): return _warping.Array_erase(self, *args)
    def __init__(self, *args): 
        this = _warping.new_Array(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _warping.Array_push_back(self, *args)
    def front(self): return _warping.Array_front(self)
    def back(self): return _warping.Array_back(self)
    def assign(self, *args): return _warping.Array_assign(self, *args)
    def resize(self, *args): return _warping.Array_resize(self, *args)
    def insert(self, *args): return _warping.Array_insert(self, *args)
    def reserve(self, *args): return _warping.Array_reserve(self, *args)
    def capacity(self): return _warping.Array_capacity(self)
    __swig_destroy__ = _warping.delete_Array
    __del__ = lambda self : None;
Array_swigregister = _warping.Array_swigregister
Array_swigregister(Array)


def init(*args):
  return _warping.init(*args)
init = _warping.init

def set_snapshot(*args):
  return _warping.set_snapshot(*args)
set_snapshot = _warping.set_snapshot

def compute_home_vector(*args):
  return _warping.compute_home_vector(*args)
compute_home_vector = _warping.compute_home_vector

def get_home_x():
  return _warping.get_home_x()
get_home_x = _warping.get_home_x

def get_home_y():
  return _warping.get_home_y()
get_home_y = _warping.get_home_y
# This file is compatible with both classic and new-style classes.


