#include Makefile.common

# Do a make on all directories.
all:
	cd utils; make; cd ..
	cd other; make; cd ..
	cd img; make; cd ..
#	cd sim; make; cd ..
	cd homing; make; cd ..
#	cd camera; make; cd ..
#	cd control; make; cd ..
#	cd exps; make; cd ..

# Do a make clean on all directories.
clean:
	cd utils; make clean; cd ..
	cd other; make clean; cd ..
	cd img; make clean; cd ..
#	cd sim; make clean; cd ..
	cd homing; make clean; cd ..
#	cd camera; make clean; cd ..
#	cd control; make clean; cd ..
#	cd exps; make clean; cd ..
